### PR TITLE
Updated Url

### LINKED ISSUE #174: chore: update token deposit RFC URL to github link
The RFC URL of the token deposit still has the gitlab link, check here: https://github.com/HathorNetwork/hathor-wallet-mobile/blob/master/src/constants.js#L48

We should use the github link instead. https://github.com/HathorNetwork/rfcs/blob/master/text/0011-token-deposit.md

### PR DESCRIPTION
**Pull request by PrajwalBorkar**
### Acceptance Criteria
- Include here all things that this PR should solve
- Fixed #174 

### Security Checklist
- [x] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

### CODE REVIEW

**Comment by pedroferreira1** [comment]
Hi @PrajwalBorkar sorry for the late reply. Can you change the target branch to `dev` please?

**Comment by pedroferreira1** [comment]
Hi @PrajwalBorkar thanks for changing the target branch. I just need to ask you to create this PR from the `dev` branch as well, otherwise there are a lot of commits that are in the `master` branch but not in the `dev` branch. 

As soon as you do it, we will start the review process and move with the merge after it's approved.

Thanks again for the contribution

**Comment by PrajwalBorkar** [comment]
Created PR from dev branch as well please review , Thanks.

**Comment by luislhl** [comment]
Closing since we now have https://github.com/HathorNetwork/hathor-wallet-mobile/pull/208

**Pull request closed without merging**
