### PR TITLE
feat(i18n): Add Danish translation

### PR DESCRIPTION
**Pull request by InfiniteDAGl00p**
Added Danish translation

### CODE REVIEW

**Comment by msbrogli** [comment]
Hi @InfiniteDAGl00p . Thanks for the Pull Request. I just updated the pot file and some strings have changed. I've merged your file with the new pot file.

Here is attached the merged PO file: [texts.po.zip](https://github.com/HathorNetwork/hathor-wallet-mobile/files/4262629/texts.po.zip).

You can safely copy to your folder and commit the changes.

There are two new strings without translation. Would you please translate them? I copied them here for you.

```
msgid "Words saved correctly"
msgstr ""
```

```
msgid "**${ _this.name }** created successfully"
msgstr ""
```

**Comment by msbrogli** [comment]
Hi @InfiniteDAGl00p, you also have to rebase to the new `origin/dev` commit.

I think the following commands should do it:

```bash
# Add upstream repo to list of remotes.
$ git remote add upstream https://github.com/HathorNetwork/hathor-wallet-mobile.git

# Fetch upstream master and merge with your repo's dev branch
$ git fetch upstream
$ git checkout dev
$ git merge upstream/dev

# Rebase your branch
$ git checkout feat/danish-translation
$ git rebase dev
```

**Comment by InfiniteDAGl00p** [comment]
Hi @msbrogli 

I think I managed to do the things you said:

I downloaded to new .po file. 
Translated the two sentences
Put it in the right folder
Merged with feat/danish-translation 
And rebased branch to upstream/dev

I hope I did everything right :)

**Comment by msbrogli** [comment]
Hi @InfiniteDAGl00p, you did everything right. Thanks!

I did a few minor changes to your branch, including a rebase to squash the commits into a single one. To update your local repository, you should run:

```
git fetch origin
git reset --hard origin/feat/danish-translation
```

I think it is ready to merge. Can you check if everything is ok, please?

If it is, I'll merge it and the Danish translation will be available in the next version of Hathor Wallet for iOS and Android.

**Pull request merged**
